# Site settings
title: Sami's home
email: 
description: "Sami's home"
keywords:
- Shanghai
- Event
- Movie
- Airbnb

# URL
url: "https://event.sayidhe.com"
baseurl: ""

# Google tracking (Analytics and Google Tag Manager)
google_tag_manager: 
google_analytics: 

# SEO
twitter: 
facebook: 
logo: /assets/logo.png
image: 
social:
  - 

# Sitemap (see sitemap.xml)
sitemap:
  changefreq: weekly

# Build settings
exclude: ['README.md', 'Makefile']

# Plugins
plugins:
- jekyll-sitemap

# Multiligual
lang:
  - zh
  - en

# sass:
#   style: compressed
